### ISSUE TITLE
Show clip info

### ISSUE THREAD

**Issue by salsatheone** [teklynk/twitch_clips_player#1]
Hello, is it possible to show the Clip title, who created, creation date and the game played during the clip?

This is the effect I would like to achieve:
![image](https://user-images.githubusercontent.com/67241281/224361201-05ae2fba-00c1-4559-b468-7ef52bbd5226.png)

This streamer is using a random clip player, but they also have all the clip info on the screen.

Thanks!

**Comment by teklynk** [comment]
This is a great idea. I will work on adding this feature. What I am thinking is adding a text area where users can format the text that appears in the panel. Something like:

{title}
While streaming {game}
Clipped by {creator_name} on {created_at}

{title},{game},{creator_name},{created_at} would act as placeholders/variables.

The css/styling could be modified in the obs browser source to achieve the look that the user wants.

**Comment by salsatheone** [comment]
Alright! Good to know cause I was looking for something like that and I have been using yours with great success so far. Thanks!

**Comment by teklynk** [comment]
I have added a simple clips details panel as an option on the overlay. 

![Screenshot from 2023-03-11 21-35-56](https://user-images.githubusercontent.com/4500737/224521259-ccc0895e-161e-4432-85ce-93912e8ba8e8.png)

![Screenshot from 2023-03-11 20-21-09](https://user-images.githubusercontent.com/4500737/224521271-555d8fc5-c455-4a29-8947-d8e312912040.png)

CSS/styling can be controlled from the OBS browser source. 
To change the background color or the panel or panel time limit, change these values and add to the browser source:

#details-container {
     background: #00000090;
     animation: fadeout 15s forwards;
}

Let me know if you have any questions or issues.

**Comment by salsatheone** [comment]
I've used it, but for whatever reason, it always shows the info of one clip and then it repeats the same info for all the clips.
![image](https://user-images.githubusercontent.com/67241281/224571930-f6fb9da7-a444-4346-89ac-ccf873f042e0.png)
![image](https://user-images.githubusercontent.com/67241281/224571954-5f5c7f5a-c355-462a-9132-4f243d007e84.png)
![image](https://user-images.githubusercontent.com/67241281/224572022-2c7a274a-0be2-4c00-ba09-e77337292a03.png)
Always the same title with these 3 different clips.

**Comment by teklynk** [comment]
Interesting. I think this may be a cache issue? In the OBS browser source, click the Refresh cache of current page. 
Also, are you running this locally or using the hosted version here: https://twitch-clips-player.pages.dev. If running locally, you may need to pull in the latest code changes from the Main branch. 

I tested this in OBS and was not able to reproduce this issue, which makes me think that it is related to browser sources cache.

**Comment by teklynk** [comment]
Also, If you want the panel to look similar to the original screenshot that you posted, try adding this CSS to the Custom CSS section of the OBS browser source.

```css
#text-container {
    background: #00008890;
    animation: fadeout 20s forwards;
}
#details-container {
    top: 35vw;
    border-radius: 24px;
    transform: skew(5deg, -5deg);
    margin-left: 20px;
    background: #00008890;
    border: solid 2px #00008898;
    box-shadow: 10px 10px #00000090;
    animation: fadeout 20s forwards;
}
#details-container .details-text.item-0 {
    font-size: 4vw;
}

#details-container .details-text.item-1 {
    font-size: 3vw;
}

#details-container .details-text.item-2 {
    font-size: 2vw;
}

#details-container .details-text.item-3 {
    font-size: 1.5vw;
}
```
![Screenshot from 2023-03-12 17-25-12](https://user-images.githubusercontent.com/4500737/224574595-ffa0ead5-ef5d-4d60-ba83-d5f328a5658d.png)
