### ISSUE TITLE
Handling of none 16:9 Clips

### ISSUE THREAD

**Issue by Gol-D-Ace** [teklynk/twitch_clips_player#21]
Hi

Guess this is a bit of a niche request but I'm gonna try my luck anyways.

I have a clips that aren't 16:9 from old games like for example:  https://clips.twitch.tv/SuspiciousElegantVelociraptorBuddhaBar

They get cut off in a 1280x720 browser source.

Any way they could be scaled to fit properly into the 16:9 player?

Thank you

**Comment by teklynk** [comment]
Hello @Gol-D-Ace 

One thing you can try is add custom CSS to the browser source properties.

```css
video {
    width: 1280px !important;
    height: 720px !important;
    background: black;
}
```

This should force the video player to 1280x720. 

![Image](https://github.com/user-attachments/assets/fdff67cc-70ad-4163-8f1c-66a0772926e4)
